service: api-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: arun-practice
  deploymentPrefix: lambda/auction-service
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTableResource.yml):AuctionsTableResource}
  Outputs:
    AuctionsTableArn:
      Description: "AuctionsTable arn"
      Value: !GetAtt AuctionsTable.Arn
      Export:
        Name: AuctionsTableArn-${self:provider.stage}

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          method: GET
          path: /hello
  createAuction:
    handler: src/index.createAuction
    events:
      - http:
          method: POST
          path: /auction
          authorizer:
            name: AuctionAuth
            type: COGNITO_USER_POOLS
            arn: "${self:custom.CognitoUserPool.Arn}"
            claims:
              - "email"
  getAuctions:
    handler: src/index.getAuctions
    events:
      - http:
          method: GET
          path: /auction
          authorizer:
            name: AuctionAuth
            type: COGNITO_USER_POOLS
            arn: "${self:custom.CognitoUserPool.Arn}"
            claims:
              - "email"
  getAuction:
    handler: src/index.getAuction
    events:
      - http:
          method: GET
          path: /auction/{id}
          authorizer:
            name: AuctionAuth
            type: COGNITO_USER_POOLS
            arn: "${self:custom.CognitoUserPool.Arn}"
            claims:
              - "email"
  placeBid:
    handler: src/index.placeBid
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
          authorizer:
            name: AuctionAuth
            type: COGNITO_USER_POOLS
            arn: "${self:custom.CognitoUserPool.Arn}"
            claims:
              - "email"

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  CognitoUserPool:
    Arn:
      Fn::ImportValue: UserPoolArn-${self:provider.stage}
